import Footer from "./components/Footer";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Metropoly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-full">
        <div className="flex flex-col lg:flex-row w-full">
          <Sidebar />

          <div className="flex-1 flex flex-col bg-white">
            <Header />
            <main className="flex-1 w-full">{children}</main>
          </div>
        </div>

        <Footer />
      </body>
    </html>
  );
}
